package editor

import (
	"bufio"
	"bytes"
	"context"
	"fmt"
	"io"
	"os/exec"
	"strconv"
	"strings"

	"github.com/rechedev9/cliphub/internal/filecommit"
)

func parseFFmpegProgressOutTimeUs(content string) (int64, bool) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	var outTimeUs int64
	found := false
	for scanner.Scan() {
		if value, ok := parseFFmpegOutTimeLine(scanner.Text()); ok {
			outTimeUs, found = value, true
		}
	}
	return outTimeUs, found
}

func parseFFmpegOutTimeLine(line string) (int64, bool) {
	line = strings.TrimSpace(line)
	value, ok := strings.CutPrefix(line, "out_time_us=")
	if !ok {
		return 0, false
	}
	parsed, err := strconv.ParseInt(value, 10, 64)
	return parsed, err == nil && parsed >= 0
}

func ffmpegEncodeFraction(outTimeUs int64, expectedDurationSec float64) (float64, bool) {
	if expectedDurationSec <= 0 || outTimeUs <= 0 {
		return 0, false
	}
	frac := float64(outTimeUs) / 1e6 / expectedDurationSec
	if frac < 0 {
		return 0, false
	}
	if frac > 0.99 {
		frac = 0.99
	}
	return frac, true
}

func appendFFmpegProgressArgs(command []string, progressPath string) []string {
	if progressPath == "" || len(command) == 0 {
		return command
	}
	out := make([]string, 0, len(command)+4)
	out = append(out, command[0])
	out = append(out, "-progress", progressPath, "-nostats")
	out = append(out, command[1:]...)
	return out
}

func runFFmpegOutputWithProgress(
	ctx context.Context,
	command []string,
	label string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	_, err := runFFmpegOutputProgress(ctx, command, label, expectedDurationSec, onFraction)
	return err
}

// Keep stderr available for callers that parse FFmpeg's loudness evidence.
func runFFmpegOutputProgress(ctx context.Context, command []string, label string, expectedDurationSec float64, onFraction func(float64)) (string, error) {
	return runFFmpegOutputProgressTo(ctx, command, label, expectedDurationSec, onFraction, nil)
}

// Progress can also certify a complete decode without a second media pass.
// Keep that stdout evidence separate from stderr loudness measurements.
func runFFmpegOutputProgressTo(ctx context.Context, command []string, label string, expectedDurationSec float64, onFraction func(float64), progressOutput io.Writer) (string, error) {
	if (onFraction == nil || expectedDurationSec <= 0) && progressOutput == nil {
		return runFFmpegOutput(ctx, command, label)
	}
	if onFraction == nil {
		onFraction = func(float64) {}
	}
	// FFmpeg owns stdout exclusively for progress; no growing temporary file,
	// polling goroutine, or repeated reads of all prior progress records.
	command = appendFFmpegProgressArgs(command, "pipe:1")
	if len(command) == 0 || command[0] == "" {
		return "", fmt.Errorf("ffmpeg command is empty")
	}
	if label == "" {
		label = "command"
	}
	command, cleanup, err := commandWithFilterComplexScript(command)
	if err != nil {
		return "", err
	}
	defer cleanup()

	// os/exec serializes Write calls and joins its pipe copier before Run returns.
	// Cancellation therefore cannot leave a progress callback in flight.
	progress := &ffmpegProgressWriter{duration: expectedDurationSec, onFraction: onFraction}
	var out bytes.Buffer
	// #nosec G204 -- commands are generated by this package as argument slices, not shell strings.
	cmd := exec.CommandContext(ctx, command[0], command[1:]...)
	cmd.Stdout = progress
	if progressOutput != nil {
		cmd.Stdout = io.MultiWriter(progress, progressOutput)
	}
	cmd.Stderr = &out
	err = runDiagnosticFFmpeg(ctx, cmd, label)
	output := out.String()
	if err != nil {
		msg := strings.TrimSpace(output)
		if msg != "" {
			return output, fmt.Errorf("ffmpeg %s: %w: %s", label, err, msg)
		}
		return output, fmt.Errorf("ffmpeg %s: %w", label, err)
	}
	return output, nil
}

// Retains at most one bounded partial line across arbitrary pipe chunks.
// Unexpected oversized output is discarded through its newline, never allowed
// to back up FFmpeg's stdout or masquerade as a progress record.
type ffmpegProgressWriter struct {
	duration     float64
	onFraction   func(float64)
	pending      []byte
	discarding   bool
	lastFraction float64
}

func (w *ffmpegProgressWriter) Write(data []byte) (int, error) {
	n := len(data)
	for len(data) > 0 {
		end := bytes.IndexByte(data, '\n')
		part := data
		if end >= 0 {
			part = data[:end]
		}
		if !w.discarding {
			if len(w.pending)+len(part) > 4096 {
				w.pending = w.pending[:0]
				w.discarding = true
			} else {
				w.pending = append(w.pending, part...)
			}
		}
		if end < 0 {
			break
		}
		if !w.discarding {
			if us, ok := parseFFmpegOutTimeLine(string(w.pending)); ok {
				if fraction, ok := ffmpegEncodeFraction(us, w.duration); ok && fraction > w.lastFraction {
					w.lastFraction = fraction
					w.onFraction(fraction)
				}
			}
		}
		w.pending = w.pending[:0]
		w.discarding = false
		data = data[end+1:]
	}
	return n, nil
}

func runFFmpegWithOptionalLogAndProgress(
	ctx context.Context,
	command []string,
	label, logPath string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	var output string
	var err error
	if onFraction != nil && expectedDurationSec > 0 {
		err = runFFmpegOutputWithProgress(ctx, command, label, expectedDurationSec, onFraction)
	} else {
		output, err = runFFmpegOutput(ctx, command, label)
	}
	if err != nil && logPath != "" {
		if strings.TrimSpace(output) == "" {
			output = err.Error() + "\n"
		}
		_ = writeLogFile(logPath, output)
	}
	return err
}

func runFFmpegAtomicWithProgress(
	ctx context.Context,
	command []string,
	label, logPath, destination string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	if len(command) == 0 || destination == "" {
		return fmt.Errorf("%s output path is required", label)
	}
	attempt, cleanup, err := filecommit.Attempt(destination)
	if err != nil {
		return fmt.Errorf("%s attempt: %w", label, err)
	}
	defer cleanup()
	attemptCommand := append([]string(nil), command...)
	if attemptCommand[len(attemptCommand)-1] != destination {
		return fmt.Errorf("%s command output does not match destination", label)
	}
	attemptCommand[len(attemptCommand)-1] = attempt
	if err := runFFmpegWithOptionalLogAndProgress(ctx, attemptCommand, label, logPath, expectedDurationSec, onFraction); err != nil {
		return err
	}
	if err := filecommit.Commit(attempt, destination); err != nil {
		return fmt.Errorf("%s publish: %w", label, err)
	}
	return nil
}
