package editor

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/rechedev9/cliphub/internal/filecommit"
)

const ffmpegProgressPollInterval = 250 * time.Millisecond

func parseFFmpegProgressOutTimeUs(content string) (int64, bool) {
	scanner := bufio.NewScanner(strings.NewReader(content))
	var outTimeUs int64
	found := false
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "out_time_us=") {
			continue
		}
		value := strings.TrimPrefix(line, "out_time_us=")
		if value == "N/A" {
			continue
		}
		parsed, err := strconv.ParseInt(value, 10, 64)
		if err != nil || parsed < 0 {
			continue
		}
		outTimeUs = parsed
		found = true
	}
	return outTimeUs, found
}

func ffmpegEncodeFraction(outTimeUs int64, expectedDurationSec float64) (float64, bool) {
	if expectedDurationSec <= 0 || outTimeUs <= 0 {
		return 0, false
	}
	frac := float64(outTimeUs) / 1e6 / expectedDurationSec
	if frac < 0 {
		return 0, false
	}
	if frac > 0.99 {
		frac = 0.99
	}
	return frac, true
}

func appendFFmpegProgressArgs(command []string, progressPath string) []string {
	if progressPath == "" || len(command) == 0 {
		return command
	}
	out := make([]string, 0, len(command)+4)
	out = append(out, command[0])
	out = append(out, "-progress", progressPath, "-nostats")
	out = append(out, command[1:]...)
	return out
}

func runFFmpegOutputWithProgress(
	ctx context.Context,
	command []string,
	label string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	if onFraction == nil || expectedDurationSec <= 0 {
		_, err := runFFmpegOutput(ctx, command, label)
		return err
	}
	progressFile, err := os.CreateTemp("", "cliphub-ffmpeg-progress-*.txt")
	if err != nil {
		_, err := runFFmpegOutput(ctx, command, label)
		return err
	}
	progressPath := progressFile.Name()
	_ = progressFile.Close()
	defer os.Remove(progressPath)

	command = appendFFmpegProgressArgs(command, progressPath)
	if len(command) == 0 || command[0] == "" {
		return fmt.Errorf("ffmpeg command is empty")
	}
	if label == "" {
		label = "command"
	}
	command, cleanup, err := commandWithFilterComplexScript(command)
	if err != nil {
		return err
	}
	defer cleanup()

	watchCtx, cancel := context.WithCancel(ctx)
	defer cancel()
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		watchFFmpegProgressFile(watchCtx, progressPath, expectedDurationSec, onFraction)
	}()

	// #nosec G204 -- commands are generated by this package as argument slices, not shell strings.
	cmd := exec.CommandContext(ctx, command[0], command[1:]...)
	out, err := cmd.CombinedOutput()
	cancel()
	wg.Wait()
	output := string(out)
	if err != nil {
		msg := strings.TrimSpace(output)
		if msg != "" {
			return fmt.Errorf("ffmpeg %s: %w: %s", label, err, msg)
		}
		return fmt.Errorf("ffmpeg %s: %w", label, err)
	}
	return nil
}

func watchFFmpegProgressFile(
	ctx context.Context,
	path string,
	expectedDurationSec float64,
	onFraction func(float64),
) {
	ticker := time.NewTicker(ffmpegProgressPollInterval)
	defer ticker.Stop()
	var lastFrac float64
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			body, err := os.ReadFile(path)
			if err != nil {
				continue
			}
			outTimeUs, ok := parseFFmpegProgressOutTimeUs(string(body))
			if !ok {
				continue
			}
			frac, ok := ffmpegEncodeFraction(outTimeUs, expectedDurationSec)
			if !ok || frac < lastFrac {
				continue
			}
			lastFrac = frac
			onFraction(frac)
		}
	}
}

func runFFmpegWithOptionalLogAndProgress(
	ctx context.Context,
	command []string,
	label, logPath string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	var output string
	var err error
	if onFraction != nil && expectedDurationSec > 0 {
		err = runFFmpegOutputWithProgress(ctx, command, label, expectedDurationSec, onFraction)
	} else {
		output, err = runFFmpegOutput(ctx, command, label)
	}
	if err != nil && logPath != "" {
		if strings.TrimSpace(output) == "" {
			output = err.Error() + "\n"
		}
		_ = writeLogFile(logPath, output)
	}
	return err
}

func runFFmpegAtomicWithProgress(
	ctx context.Context,
	command []string,
	label, logPath, destination string,
	expectedDurationSec float64,
	onFraction func(float64),
) error {
	if len(command) == 0 || destination == "" {
		return fmt.Errorf("%s output path is required", label)
	}
	attempt, cleanup, err := filecommit.Attempt(destination)
	if err != nil {
		return fmt.Errorf("%s attempt: %w", label, err)
	}
	defer cleanup()
	attemptCommand := append([]string(nil), command...)
	if attemptCommand[len(attemptCommand)-1] != destination {
		return fmt.Errorf("%s command output does not match destination", label)
	}
	attemptCommand[len(attemptCommand)-1] = attempt
	if err := runFFmpegWithOptionalLogAndProgress(ctx, attemptCommand, label, logPath, expectedDurationSec, onFraction); err != nil {
		return err
	}
	if err := filecommit.Commit(attempt, destination); err != nil {
		return fmt.Errorf("%s publish: %w", label, err)
	}
	return nil
}
