allowBuilds:
  electron-winstaller: true
overrides:
  brace-expansion: 5.0.8
minimumReleaseAgeExclude:
  - brace-expansion@1.1.16 || 2.1.2
  - fast-uri@3.1.4
patchedDependencies:
  brace-expansion@5.0.8: patches/brace-expansion@5.0.8.patch
